# Generated by Django 5.1.6 on 2025-06-02 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_lead_modified_at_alter_lead_email_alter_lead_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.AddField(
            model_name='lead',
            name='agent_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Agent Comment'),
        ),
        migrations.AddField(
            model_name='lead',
            name='manager_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Manager Comment'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Agent'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='General Comment'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(help_text='Enter a valid email address', max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='full_name',
            field=models.CharField(help_text='Enter the full name of the lead', max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='income_range',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Income Range'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(help_text='Enter a valid phone number', max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Timezone'),
        ),
    ]
